### PR TITLE
implemented humanoid bench tasks with unitree H1 robot in mujoco mpc

### PR DESCRIPTION
**Pull request by MoritzMeser**

### CODE REVIEW

**Comment by thowell** [comment]
Thanks for the contribution! It looks like these tasks are based on [HumanoidBench](https://humanoid-bench.github.io/)? What kinds of success are you seeing with these tasks using MJPC?

**Comment by MoritzMeser** [comment]
That's right, it's based on HumanoidBench. 

The success of tasks like standing and walking is very good. In terms of reward, these tasks are as good as solved, even if the behavior seems very unrealistic. (Like jumping on one leg). 

However, there is no success in more complicated tasks, where the robot has to interact with objects.

**Comment by MoritzMeser** [comment]
Thanks for taking the time to review my pull request. Your plan sounds like a good approach to manage this integration.

I will reach out to you once the steps you mention are implemented. 

Thanks again for your guidance. I look forward to our collaboration.

**Comment by MoritzMeser** [comment]
I have fixed the issues we discussed above. 
Now I would like to make a new pull request.

There is only one problem. The git tag for menagerie on the main branch is too old to load the G1 model. 
There is a second branch called "deepmind". It already has the new git tag, so loading the G1 model works there. 

Should I just make a pull request to merge into the "deepmind" branch instead of the "main" branch?

**Comment by thowell** [comment]
@MoritzMeser you can update the [git tag](https://github.com/google-deepmind/mujoco_mpc/blob/1f78168912b4fe4af30365198c9f4e3ecf025ba1/CMakeLists.txt#L64) for the latest version of Menagerie in your new PR. Thanks!

**Pull request closed without merging**
